const { app, BrowserWindow, ipcMain, dialog, shell } = require('electron');
const path = require('node:path');
const fs = require('node:fs');
const { spawn } = require('node:child_process');
const { DatabaseSync } = require('node:sqlite');
const { Pool } = require('pg');
const bcrypt = require('bcryptjs');

const APP_NAME = 'United Agencies karachi';
const COMPANY = 'TechSaws';

function getAppDataDir() {
  const base = process.env.APPDATA || process.env.LOCALAPPDATA;
  if (base) {
    const target = path.join(base, COMPANY, APP_NAME);
    fs.mkdirSync(target, { recursive: true });
    return target;
  }

  const fallback = path.join(__dirname, 'data');
  fs.mkdirSync(fallback, { recursive: true });
  return fallback;
}

function getDbPath() {
  return path.join(getAppDataDir(), 'database.db');
}

function getDbConfigPath() {
  return path.join(getAppDataDir(), 'db.config.json');
}

function getPythonPath() {
  const bundled = path.join(__dirname, '..', 'venv', 'Scripts', 'python.exe');
  if (fs.existsSync(bundled)) {
    return bundled;
  }
  return 'python';
}

function getInvoicesDir() {
  const docs = app.getPath('documents');
  const target = path.join(docs, 'UnitedAgenciesKarachiInvoices');
  fs.mkdirSync(target, { recursive: true });
  return target;
}

function getOrdersDir() {
  const docs = app.getPath('documents');
  const target = path.join(docs, 'UnitedAgenciesKarachiOrders');
  fs.mkdirSync(target, { recursive: true });
  return target;
}

function parseJsonFile(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch (_error) {
    return null;
  }
}

function getPostgresConfig() {
  if (process.env.POSTGRES_URL) {
    return {
      connectionString: process.env.POSTGRES_URL,
    };
  }

  const candidatePaths = [
    path.join(__dirname, 'db.config.json'),
    getDbConfigPath(),
  ];

  for (const candidatePath of candidatePaths) {
    if (!fs.existsSync(candidatePath)) continue;
    const config = parseJsonFile(candidatePath);
    if (!config) continue;

    if (config.connectionString) {
      return {
        connectionString: config.connectionString,
      };
    }

    if (config.host && config.user && config.database) {
      return {
        host: config.host,
        port: Number(config.port || 5432),
        user: config.user,
        password: config.password || '',
        database: config.database,
        ssl: config.ssl ? { rejectUnauthorized: false } : false,
      };
    }
  }

  return null;
}

function isPostgresConfigured() {
  return !!getPostgresConfig();
}

let pgPool = null;

function getPgPool() {
  if (pgPool) {
    return pgPool;
  }

  const config = getPostgresConfig();
  if (!config) {
    throw new Error(
      `PostgreSQL is not configured. Create ${getDbConfigPath()} with your office database settings or set POSTGRES_URL.`
    );
  }

  pgPool = new Pool({
    ...config,
    max: 10,
  });
  return pgPool;
}

function toIsoTimestamp(value) {
  if (!value) return '';
  if (value instanceof Date) return value.toISOString();
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? String(value) : parsed.toISOString();
}

function toIsoDate(value) {
  if (!value) return '';
  if (value instanceof Date) return value.toISOString().slice(0, 10);
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? String(value).slice(0, 10) : parsed.toISOString().slice(0, 10);
}

async function ensureSchemaPg() {
  const pool = getPgPool();
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      role TEXT NOT NULL DEFAULT 'user'
    );

    CREATE TABLE IF NOT EXISTS invoices (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      invoice_no TEXT,
      customer_name TEXT,
      total NUMERIC(14,2),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      service_type TEXT,
      phone TEXT,
      paid_amount NUMERIC(14,2),
      payment_mode TEXT,
      str_no TEXT,
      ntn_no TEXT,
      bill_no TEXT,
      delivery_challan_no TEXT,
      order_contract_no TEXT,
      order_date DATE,
      inspection_note_no TEXT,
      invoice_date DATE,
      to_text TEXT
    );

    CREATE TABLE IF NOT EXISTS inventory_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      reg_no TEXT,
      batch_no TEXT,
      mfg_date DATE,
      exp_date DATE,
      quantity NUMERIC(14,2),
      product_description TEXT,
      trade_price NUMERIC(14,2),
      discount_percent NUMERIC(14,2),
      price_per_unit NUMERIC(14,2),
      amount_pkr NUMERIC(14,2),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS invoice_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      invoice_id INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
      inventory_item_id INTEGER REFERENCES inventory_items(id),
      product_description TEXT,
      quantity NUMERIC(14,2),
      unit_price NUMERIC(14,2)
    );

    CREATE TABLE IF NOT EXISTS orders (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      institution_name TEXT,
      order_number TEXT,
      order_date DATE,
      file_name TEXT,
      file_path TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS payments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      invoice_id INTEGER UNIQUE REFERENCES invoices(id) ON DELETE CASCADE,
      bill_no TEXT,
      institution_name TEXT,
      invoice_date DATE,
      status TEXT NOT NULL DEFAULT 'pending',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  `);

  await pool.query(`UPDATE users SET role='user' WHERE role IS NULL OR role=''`);
  await pool.query(`UPDATE users SET role='admin' WHERE username='admin' AND role <> 'admin'`);
  await pool.query(`
    INSERT INTO payments (
      invoice_id,
      bill_no,
      institution_name,
      invoice_date,
      status,
      created_at
    )
    SELECT
      invoices.id,
      invoices.bill_no,
      invoices.customer_name,
      invoices.invoice_date,
      'pending',
      invoices.created_at
    FROM invoices
    ON CONFLICT (invoice_id) DO NOTHING
  `);

  const users = [
    { username: 'admin', password: 'myadmin786', role: 'admin' },
    { username: 'user', password: 'user123', role: 'user' },
  ];

  for (const entry of users) {
    const existing = await pool.query('SELECT id FROM users WHERE username = $1', [entry.username]);
    if (existing.rowCount === 0) {
      const hash = await bcrypt.hash(entry.password, 10);
      await pool.query(
        'INSERT INTO users (username, password_hash, role) VALUES ($1, $2, $3)',
        [entry.username, hash, entry.role]
      );
    }
  }
}

async function authenticatePg(username, password) {
  const pool = getPgPool();
  const result = await pool.query(
    'SELECT password_hash, role FROM users WHERE username = $1',
    [username]
  );

  if (result.rowCount === 0) {
    return { ok: false, role: null };
  }

  const row = result.rows[0];
  const valid = await bcrypt.compare(password, row.password_hash || '');
  if (!valid) {
    return { ok: false, role: null };
  }

  return { ok: true, role: row.role || 'user' };
}

async function listInvoicesPg() {
  const pool = getPgPool();
  const result = await pool.query(`
    SELECT
      id,
      invoice_no,
      bill_no,
      delivery_challan_no,
      order_contract_no,
      inspection_note_no,
      to_text,
      invoice_date,
      order_date,
      total,
      created_at
    FROM invoices
    ORDER BY created_at DESC
  `);

  return result.rows.map((row) => ({
    id: row.id,
    fileNo: row.invoice_no || '',
    billNo: row.bill_no || '',
    deliveryChallanNo: row.delivery_challan_no || '',
    orderContractNo: row.order_contract_no || '',
    inspectionNoteNo: row.inspection_note_no || '',
    toText: row.to_text || '',
    invoiceDate: toIsoDate(row.invoice_date),
    orderDate: toIsoDate(row.order_date),
    totalQty: Number(row.total || 0),
    createdAt: toIsoTimestamp(row.created_at),
  }));
}

async function listInventoryPg() {
  const pool = getPgPool();
  const result = await pool.query(`
    SELECT
      id,
      reg_no,
      batch_no,
      mfg_date,
      exp_date,
      quantity,
      product_description,
      trade_price,
      discount_percent,
      created_at
    FROM inventory_items
    ORDER BY created_at DESC
  `);

  return result.rows.map((row) => ({
    id: row.id,
    regNo: row.reg_no || '',
    batchNo: row.batch_no || '',
    mfgDate: toIsoDate(row.mfg_date),
    expDate: toIsoDate(row.exp_date),
    quantity: Number(row.quantity || 0),
    productDescription: row.product_description || '',
    tradePrice: Number(row.trade_price || 0),
    discountPercent: Number(row.discount_percent || 0),
    createdAt: toIsoTimestamp(row.created_at),
  }));
}

async function listOrdersPg() {
  const pool = getPgPool();
  const result = await pool.query(`
    SELECT
      id,
      institution_name,
      order_number,
      order_date,
      file_name,
      file_path,
      created_at
    FROM orders
    ORDER BY created_at DESC
  `);

  return result.rows.map((row) => ({
    id: row.id,
    institutionName: row.institution_name || '',
    orderNumber: row.order_number || '',
    orderDate: toIsoDate(row.order_date),
    fileName: row.file_name || '',
    filePath: row.file_path || '',
    createdAt: toIsoTimestamp(row.created_at),
  }));
}

async function listPaymentsPg() {
  const pool = getPgPool();
  const result = await pool.query(`
    SELECT
      id,
      invoice_id,
      bill_no,
      institution_name,
      invoice_date,
      status,
      created_at
    FROM payments
    ORDER BY created_at DESC
  `);

  return result.rows.map((row) => ({
    id: row.id,
    invoiceId: row.invoice_id,
    billNo: row.bill_no || '',
    institutionName: row.institution_name || '',
    invoiceDate: toIsoDate(row.invoice_date),
    status: (row.status || 'pending').toLowerCase(),
    createdAt: toIsoTimestamp(row.created_at),
  }));
}

async function getInvoicePdfPayloadPg(invoiceId) {
  const pool = getPgPool();
  const invoiceResult = await pool.query(`
    SELECT
      id,
      invoice_no,
      bill_no,
      delivery_challan_no,
      order_contract_no,
      order_date,
      inspection_note_no,
      invoice_date,
      to_text
    FROM invoices
    WHERE id = $1
  `, [invoiceId]);

  if (invoiceResult.rowCount === 0) {
    throw new Error('Invoice not found.');
  }

  const invoice = invoiceResult.rows[0];
  const itemsResult = await pool.query(`
    SELECT
      ii.quantity,
      ii.unit_price,
      ii.product_description,
      inv.reg_no,
      inv.batch_no,
      inv.mfg_date,
      inv.exp_date
    FROM invoice_items ii
    LEFT JOIN inventory_items inv ON inv.id = ii.inventory_item_id
    WHERE ii.invoice_id = $1
    ORDER BY ii.id ASC
  `, [invoiceId]);

  return {
    fileNo: invoice.invoice_no || String(invoice.id),
    billNo: invoice.bill_no || '',
    outputDir: getInvoicesDir(),
    deliveryChallanNo: invoice.delivery_challan_no || '',
    orderContractNo: invoice.order_contract_no || '',
    orderDate: toIsoDate(invoice.order_date),
    inspectionNoteNo: invoice.inspection_note_no || '',
    invoiceDate: toIsoDate(invoice.invoice_date),
    toText: invoice.to_text || '',
    products: itemsResult.rows.map((item) => ({
      regNo: item.reg_no || '',
      batchNo: item.batch_no || '',
      mfgDate: toIsoDate(item.mfg_date),
      expDate: toIsoDate(item.exp_date),
      productDescription: item.product_description || '',
      quantity: Number(item.quantity || 0),
      unitPrice: Number(item.unit_price || 0),
    })),
  };
}

async function saveInventoryItemPg(payload) {
  const pool = getPgPool();
  await pool.query(`
    INSERT INTO inventory_items (
      reg_no,
      batch_no,
      mfg_date,
      exp_date,
      quantity,
      product_description,
      trade_price,
      discount_percent,
      price_per_unit,
      amount_pkr,
      created_at
    )
    VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
  `, [
    payload.regNo,
    payload.batchNo,
    payload.mfgDate || null,
    payload.expDate || null,
    payload.quantity,
    payload.productDescription,
    payload.tradePrice,
    payload.discountPercent,
    0,
    0,
    new Date(),
  ]);
  return { ok: true };
}

async function updateInventoryItemPg(payload) {
  const pool = getPgPool();
  await pool.query(`
    UPDATE inventory_items
    SET reg_no = $1, batch_no = $2, mfg_date = $3, exp_date = $4, quantity = $5,
        product_description = $6, trade_price = $7, discount_percent = $8
    WHERE id = $9
  `, [
    payload.regNo,
    payload.batchNo,
    payload.mfgDate || null,
    payload.expDate || null,
    payload.quantity,
    payload.productDescription,
    payload.tradePrice,
    payload.discountPercent,
    payload.id,
  ]);
  return { ok: true };
}

async function saveOrderPg(payload) {
  const institutionName = String(payload.institutionName || '').trim();
  const orderNumber = String(payload.orderNumber || '').trim();
  const orderDate = String(payload.orderDate || '').trim();
  const sourceFilePath = String(payload.sourceFilePath || '').trim();

  if (!institutionName || !orderNumber || !orderDate || !sourceFilePath) {
    throw new Error('Institution name, order number, order date, and file are required.');
  }

  if (!fs.existsSync(sourceFilePath)) {
    throw new Error('Selected file could not be found.');
  }

  const ext = path.extname(sourceFilePath).toLowerCase();
  const allowedExtensions = new Set(['.pdf', '.png', '.jpg', '.jpeg', '.webp', '.bmp']);
  if (!allowedExtensions.has(ext)) {
    throw new Error('Only PDF and image files are allowed.');
  }

  const originalName = path.basename(sourceFilePath);
  const safeBase = originalName.replace(/[^\w.-]+/g, '_');
  const targetName = `${Date.now()}-${safeBase}`;
  const targetPath = path.join(getOrdersDir(), targetName);
  fs.copyFileSync(sourceFilePath, targetPath);

  const pool = getPgPool();
  const result = await pool.query(`
    INSERT INTO orders (
      institution_name,
      order_number,
      order_date,
      file_name,
      file_path,
      created_at
    )
    VALUES ($1,$2,$3,$4,$5,$6)
    RETURNING id
  `, [
    institutionName,
    orderNumber,
    orderDate || null,
    originalName,
    targetPath,
    new Date(),
  ]);

  return {
    ok: true,
    orderId: Number(result.rows[0].id),
    filePath: targetPath,
  };
}

async function updatePaymentStatusPg(payload) {
  const paymentId = Number(payload.paymentId);
  const status = String(payload.status || '').trim().toLowerCase();

  if (!paymentId) {
    throw new Error('Payment ID is required.');
  }

  if (!['pending', 'received'].includes(status)) {
    throw new Error('Invalid payment status.');
  }

  const pool = getPgPool();
  await pool.query('UPDATE payments SET status = $1 WHERE id = $2', [status, paymentId]);
  return { ok: true };
}

async function saveInvoicePg(payload) {
  if (!Array.isArray(payload.products) || payload.products.length === 0) {
    throw new Error('Please select at least one product.');
  }

  const pool = getPgPool();
  const client = await pool.connect();

  try {
    await client.query('BEGIN');

    const lockedInventory = new Map();
    for (const item of payload.products) {
      const rowResult = await client.query(`
        SELECT id, quantity, reg_no, batch_no, mfg_date, exp_date, product_description
        FROM inventory_items
        WHERE id = $1
        FOR UPDATE
      `, [item.inventoryItemId]);

      if (rowResult.rowCount === 0) {
        throw new Error('A selected product no longer exists in inventory.');
      }

      const row = rowResult.rows[0];
      const available = Number(row.quantity || 0);
      const qty = Number(item.quantity || 0);
      if (qty <= 0) {
        throw new Error('Selected product quantity must be greater than zero.');
      }
      if (qty > available) {
        throw new Error(`Insufficient stock for product ID ${item.inventoryItemId}. Available: ${available.toFixed(2)}`);
      }
      lockedInventory.set(item.inventoryItemId, row);
    }

    const createdAt = new Date();
    const invoiceDate = payload.invoiceDate || createdAt.toISOString().slice(0, 10);
    const toText = (payload.toText || '').trim();
    const totalQty = payload.products.reduce((sum, item) => sum + Number(item.quantity || 0), 0);
    const customerName = toText ? toText.split(/\r?\n/)[0] : '';
    const serviceType = payload.products.map((item) => item.productDescription || '').join(', ');

    const invoiceResult = await client.query(`
      INSERT INTO invoices (
        invoice_no, customer_name, total, created_at, service_type, phone, paid_amount,
        payment_mode, str_no, ntn_no, bill_no, delivery_challan_no, order_contract_no,
        order_date, inspection_note_no, invoice_date, to_text
      )
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
      RETURNING id
    `, [
      payload.fileNo,
      customerName,
      totalQty,
      createdAt,
      serviceType,
      '',
      0,
      '',
      '',
      '',
      payload.billNo,
      payload.deliveryChallanNo,
      payload.orderContractNo,
      payload.orderDate || null,
      payload.inspectionNoteNo,
      invoiceDate,
      toText,
    ]);

    const invoiceId = Number(invoiceResult.rows[0].id);

    for (const item of payload.products) {
      await client.query(`
        INSERT INTO invoice_items (
          invoice_id, inventory_item_id, product_description, quantity, unit_price
        )
        VALUES ($1,$2,$3,$4,$5)
      `, [
        invoiceId,
        item.inventoryItemId,
        item.productDescription,
        item.quantity,
        item.unitPrice,
      ]);

      await client.query(
        'UPDATE inventory_items SET quantity = quantity - $1 WHERE id = $2',
        [item.quantity, item.inventoryItemId]
      );
    }

    await client.query(`
      INSERT INTO payments (
        invoice_id, bill_no, institution_name, invoice_date, status, created_at
      )
      VALUES ($1,$2,$3,$4,$5,$6)
      ON CONFLICT (invoice_id) DO NOTHING
    `, [
      invoiceId,
      payload.billNo,
      customerName,
      invoiceDate,
      'pending',
      createdAt,
    ]);

    await client.query('COMMIT');

    const pdfPayload = {
      fileNo: payload.fileNo || String(invoiceId),
      billNo: payload.billNo,
      outputDir: getInvoicesDir(),
      deliveryChallanNo: payload.deliveryChallanNo,
      orderContractNo: payload.orderContractNo,
      orderDate: payload.orderDate,
      inspectionNoteNo: payload.inspectionNoteNo,
      invoiceDate,
      toText,
      products: payload.products.map((item) => {
        const inventoryItem = lockedInventory.get(item.inventoryItemId) || {};
        return {
          regNo: inventoryItem.reg_no || '',
          batchNo: inventoryItem.batch_no || '',
          mfgDate: toIsoDate(inventoryItem.mfg_date),
          expDate: toIsoDate(inventoryItem.exp_date),
          productDescription: inventoryItem.product_description || item.productDescription || '',
          quantity: item.quantity,
          unitPrice: item.unitPrice,
        };
      }),
    };

    try {
      const pdfResult = await generateInvoicePdf(pdfPayload);
      return {
        ok: true,
        invoiceId,
        pdfPath: pdfResult.path || '',
      };
    } catch (pdfError) {
      return {
        ok: true,
        invoiceId,
        pdfPath: '',
        pdfError: pdfError.message,
      };
    }
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}

async function bootstrapDataLayer() {
  if (isPostgresConfigured()) {
    await ensureSchemaPg();
    return {
      mode: 'postgres',
      configPath: getDbConfigPath(),
    };
  }

  ensureSchema();
  await runPythonHelper(['bootstrap', getDbPath()]);
  return {
    mode: 'sqlite',
    dbPath: getDbPath(),
    appDataDir: getAppDataDir(),
  };
}

async function authenticate(credentials) {
  if (isPostgresConfigured()) {
    return authenticatePg(credentials.username || '', credentials.password || '');
  }

  return runPythonHelper(['authenticate', getDbPath(), credentials.username || '', credentials.password || '']);
}

async function listInvoicesAny() {
  return isPostgresConfigured() ? listInvoicesPg() : listInvoices();
}

async function listInventoryAny() {
  return isPostgresConfigured() ? listInventoryPg() : listInventory();
}

async function listOrdersAny() {
  return isPostgresConfigured() ? listOrdersPg() : listOrders();
}

async function listPaymentsAny() {
  return isPostgresConfigured() ? listPaymentsPg() : listPayments();
}

async function saveInventoryItemAny(payload) {
  return isPostgresConfigured() ? saveInventoryItemPg(payload) : { ok: !!saveInventoryItem(payload) || true };
}

async function updateInventoryItemAny(payload) {
  return isPostgresConfigured() ? updateInventoryItemPg(payload) : { ok: !!updateInventoryItem(payload) || true };
}

async function saveOrderAny(payload) {
  return isPostgresConfigured() ? saveOrderPg(payload) : saveOrder(payload);
}

async function updatePaymentStatusAny(payload) {
  return isPostgresConfigured() ? updatePaymentStatusPg(payload) : updatePaymentStatus(payload);
}

async function saveInvoiceAny(payload) {
  return isPostgresConfigured() ? saveInvoicePg(payload) : saveInvoice(payload);
}

async function generateInvoicePdfForInvoiceAny(invoiceId) {
  if (isPostgresConfigured()) {
    const pdfPayload = await getInvoicePdfPayloadPg(invoiceId);
    const pdfResult = await generateInvoicePdf(pdfPayload);
    return { ok: true, pdfPath: pdfResult.path || '' };
  }

  return generateInvoicePdfForInvoice(invoiceId);
}

function runPythonHelper(args) {
  const helperPath = path.join(__dirname, 'backend', 'auth_helper.py');

  return new Promise((resolve, reject) => {
    const child = spawn(getPythonPath(), [helperPath, ...args], {
      cwd: path.join(__dirname, '..'),
      windowsHide: true,
    });

    let stdout = '';
    let stderr = '';

    child.stdout.on('data', (chunk) => {
      stdout += chunk.toString();
    });

    child.stderr.on('data', (chunk) => {
      stderr += chunk.toString();
    });

    child.on('error', reject);
    child.on('close', (code) => {
      if (code !== 0) {
        reject(new Error(stderr.trim() || `Python helper exited with code ${code}`));
        return;
      }

      try {
        resolve(JSON.parse(stdout || '{}'));
      } catch (_error) {
        reject(new Error(`Invalid helper response: ${stdout}`));
      }
    });
  });
}

function runPythonScript(scriptPath, args) {
  return new Promise((resolve, reject) => {
    const child = spawn(getPythonPath(), [scriptPath, ...args], {
      cwd: path.join(__dirname, '..'),
      windowsHide: true,
    });

    let stdout = '';
    let stderr = '';

    child.stdout.on('data', (chunk) => {
      stdout += chunk.toString();
    });

    child.stderr.on('data', (chunk) => {
      stderr += chunk.toString();
    });

    child.on('error', reject);
    child.on('close', (code) => {
      if (code !== 0) {
        reject(new Error(stderr.trim() || `Python script exited with code ${code}`));
        return;
      }

      try {
        resolve(JSON.parse(stdout || '{}'));
      } catch (_error) {
        reject(new Error(`Invalid helper response: ${stdout}`));
      }
    });
  });
}

function openDatabase() {
  return new DatabaseSync(getDbPath());
}

function ensureSchema() {
  const db = openDatabase();
  db.exec(`
    CREATE TABLE IF NOT EXISTS invoices (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      invoice_no TEXT,
      customer_name TEXT,
      total REAL,
      created_at TEXT,
      service_type TEXT,
      phone TEXT,
      paid_amount REAL,
      payment_mode TEXT,
      str_no TEXT,
      ntn_no TEXT,
      bill_no TEXT,
      delivery_challan_no TEXT,
      order_contract_no TEXT,
      order_date TEXT,
      inspection_note_no TEXT,
      invoice_date TEXT,
      to_text TEXT
    );

    CREATE TABLE IF NOT EXISTS inventory_items (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      reg_no TEXT,
      batch_no TEXT,
      mfg_date TEXT,
      exp_date TEXT,
      quantity REAL,
      product_description TEXT,
      trade_price REAL,
      discount_percent REAL,
      price_per_unit REAL,
      amount_pkr REAL,
      created_at TEXT
    );

    CREATE TABLE IF NOT EXISTS invoice_items (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      invoice_id INTEGER,
      inventory_item_id INTEGER,
      product_description TEXT,
      quantity REAL,
      unit_price REAL
    );

    CREATE TABLE IF NOT EXISTS orders (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      institution_name TEXT,
      order_number TEXT,
      order_date TEXT,
      file_name TEXT,
      file_path TEXT,
      created_at TEXT
    );

    CREATE TABLE IF NOT EXISTS payments (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      invoice_id INTEGER UNIQUE,
      bill_no TEXT,
      institution_name TEXT,
      invoice_date TEXT,
      status TEXT DEFAULT 'pending',
      created_at TEXT
    );
  `);

  const orderColumns = db.prepare('PRAGMA table_info(orders)').all();
  const orderColumnNames = new Set(orderColumns.map((column) => column.name));
  if (!orderColumnNames.has('order_date')) {
    db.exec('ALTER TABLE orders ADD COLUMN order_date TEXT');
  }

  db.exec(`
    INSERT OR IGNORE INTO payments (
      invoice_id,
      bill_no,
      institution_name,
      invoice_date,
      status,
      created_at
    )
    SELECT
      invoices.id,
      invoices.bill_no,
      invoices.customer_name,
      invoices.invoice_date,
      'pending',
      invoices.created_at
    FROM invoices
    WHERE invoices.id IS NOT NULL
  `);
  db.close();
}

function listInvoices() {
  const db = openDatabase();
  const rows = db.prepare(`
    SELECT
      id,
      invoice_no,
      bill_no,
      delivery_challan_no,
      order_contract_no,
      inspection_note_no,
      to_text,
      invoice_date,
      order_date,
      total,
      created_at
    FROM invoices
    ORDER BY datetime(created_at) DESC
  `).all();
  db.close();
  return rows.map((row) => ({
    id: row.id,
    fileNo: row.invoice_no || '',
    billNo: row.bill_no || '',
    deliveryChallanNo: row.delivery_challan_no || '',
    orderContractNo: row.order_contract_no || '',
    inspectionNoteNo: row.inspection_note_no || '',
    toText: row.to_text || '',
    invoiceDate: row.invoice_date || '',
    orderDate: row.order_date || '',
    totalQty: Number(row.total || 0),
    createdAt: row.created_at || '',
  }));
}

function listInventory() {
  const db = openDatabase();
  const rows = db.prepare(`
    SELECT
      id,
      reg_no,
      batch_no,
      mfg_date,
      exp_date,
      quantity,
      product_description,
      trade_price,
      discount_percent,
      created_at
    FROM inventory_items
    ORDER BY datetime(created_at) DESC
  `).all();
  db.close();
  return rows.map((row) => ({
    id: row.id,
    regNo: row.reg_no || '',
    batchNo: row.batch_no || '',
    mfgDate: row.mfg_date || '',
    expDate: row.exp_date || '',
    quantity: Number(row.quantity || 0),
    productDescription: row.product_description || '',
    tradePrice: Number(row.trade_price || 0),
    discountPercent: Number(row.discount_percent || 0),
    createdAt: row.created_at || '',
  }));
}

function listOrders() {
  const db = openDatabase();
  const rows = db.prepare(`
      SELECT
        id,
        institution_name,
        order_number,
        order_date,
        file_name,
        file_path,
        created_at
    FROM orders
    ORDER BY datetime(created_at) DESC
  `).all();
  db.close();
  return rows.map((row) => ({
      id: row.id,
      institutionName: row.institution_name || '',
      orderNumber: row.order_number || '',
      orderDate: row.order_date || '',
      fileName: row.file_name || '',
      filePath: row.file_path || '',
      createdAt: row.created_at || '',
  }));
}

function listPayments() {
  const db = openDatabase();
  const rows = db.prepare(`
    SELECT
      id,
      invoice_id,
      bill_no,
      institution_name,
      invoice_date,
      status,
      created_at
    FROM payments
    ORDER BY datetime(created_at) DESC
  `).all();
  db.close();
  return rows.map((row) => ({
    id: row.id,
    invoiceId: row.invoice_id,
    billNo: row.bill_no || '',
    institutionName: row.institution_name || '',
    invoiceDate: row.invoice_date || '',
    status: (row.status || 'pending').toLowerCase(),
    createdAt: row.created_at || '',
  }));
}

function getInvoicePdfPayload(invoiceId) {
  const db = openDatabase();

  try {
    const invoice = db.prepare(`
      SELECT
        id,
        invoice_no,
        bill_no,
        delivery_challan_no,
        order_contract_no,
        order_date,
        inspection_note_no,
        invoice_date,
        to_text
      FROM invoices
      WHERE id = ?
    `).get(invoiceId);

    if (!invoice) {
      throw new Error('Invoice not found.');
    }

    const items = db.prepare(`
      SELECT
        ii.quantity,
        ii.unit_price,
        ii.product_description,
        inv.reg_no,
        inv.batch_no,
        inv.mfg_date,
        inv.exp_date
      FROM invoice_items ii
      LEFT JOIN inventory_items inv ON inv.id = ii.inventory_item_id
      WHERE ii.invoice_id = ?
      ORDER BY ii.id ASC
    `).all(invoiceId);

      return {
        fileNo: invoice.invoice_no || String(invoice.id),
        billNo: invoice.bill_no || '',
        outputDir: getInvoicesDir(),
        deliveryChallanNo: invoice.delivery_challan_no || '',
      orderContractNo: invoice.order_contract_no || '',
      orderDate: invoice.order_date || '',
      inspectionNoteNo: invoice.inspection_note_no || '',
        invoiceDate: invoice.invoice_date || '',
        toText: invoice.to_text || '',
        products: items.map((item) => ({
        regNo: item.reg_no || '',
        batchNo: item.batch_no || '',
        mfgDate: item.mfg_date || '',
        expDate: item.exp_date || '',
        productDescription: item.product_description || '',
        quantity: item.quantity,
        unitPrice: item.unit_price,
      })),
    };
  } finally {
    db.close();
  }
}

function saveInventoryItem(payload) {
  const db = openDatabase();
  db.prepare(`
    INSERT INTO inventory_items (
      reg_no,
      batch_no,
      mfg_date,
      exp_date,
      quantity,
      product_description,
      trade_price,
      discount_percent,
      price_per_unit,
      amount_pkr,
      created_at
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `).run(
    payload.regNo,
    payload.batchNo,
    payload.mfgDate,
    payload.expDate,
    payload.quantity,
    payload.productDescription,
    payload.tradePrice,
    payload.discountPercent,
    0,
    0,
    new Date().toISOString()
  );
  db.close();
}

function updateInventoryItem(payload) {
  const db = openDatabase();
  db.prepare(`
    UPDATE inventory_items
    SET reg_no = ?, batch_no = ?, mfg_date = ?, exp_date = ?, quantity = ?,
        product_description = ?, trade_price = ?, discount_percent = ?
    WHERE id = ?
  `).run(
    payload.regNo,
    payload.batchNo,
    payload.mfgDate,
    payload.expDate,
    payload.quantity,
    payload.productDescription,
    payload.tradePrice,
    payload.discountPercent,
    payload.id
  );
  db.close();
}

function saveOrder(payload) {
  const institutionName = String(payload.institutionName || '').trim();
  const orderNumber = String(payload.orderNumber || '').trim();
  const orderDate = String(payload.orderDate || '').trim();
  const sourceFilePath = String(payload.sourceFilePath || '').trim();

  if (!institutionName || !orderNumber || !orderDate || !sourceFilePath) {
    throw new Error('Institution name, order number, order date, and file are required.');
  }

  if (!fs.existsSync(sourceFilePath)) {
    throw new Error('Selected file could not be found.');
  }

  const ext = path.extname(sourceFilePath).toLowerCase();
  const allowedExtensions = new Set(['.pdf', '.png', '.jpg', '.jpeg', '.webp', '.bmp']);
  if (!allowedExtensions.has(ext)) {
    throw new Error('Only PDF and image files are allowed.');
  }

  const originalName = path.basename(sourceFilePath);
  const safeBase = originalName.replace(/[^\w.-]+/g, '_');
  const targetName = `${Date.now()}-${safeBase}`;
  const targetPath = path.join(getOrdersDir(), targetName);
  fs.copyFileSync(sourceFilePath, targetPath);

  const db = openDatabase();
  try {
    const createdAt = new Date().toISOString();
    const result = db.prepare(`
        INSERT INTO orders (
          institution_name,
          order_number,
          order_date,
          file_name,
          file_path,
          created_at
        )
        VALUES (?, ?, ?, ?, ?, ?)
      `).run(
        institutionName,
        orderNumber,
        orderDate,
        originalName,
        targetPath,
        createdAt
    );

    return {
      ok: true,
      orderId: Number(result.lastInsertRowid),
      filePath: targetPath,
    };
  } finally {
    db.close();
  }
}

function updatePaymentStatus(payload) {
  const paymentId = Number(payload.paymentId);
  const status = String(payload.status || '').trim().toLowerCase();

  if (!paymentId) {
    throw new Error('Payment ID is required.');
  }

  if (!['pending', 'received'].includes(status)) {
    throw new Error('Invalid payment status.');
  }

  const db = openDatabase();
  try {
    db.prepare(`
      UPDATE payments
      SET status = ?
      WHERE id = ?
    `).run(status, paymentId);
    return { ok: true };
  } finally {
    db.close();
  }
}

async function generateInvoicePdf(invoicePayload) {
  const helperPath = path.join(__dirname, 'backend', 'invoice_pdf.py');
  const tempPayloadPath = path.join(getAppDataDir(), `invoice-payload-${Date.now()}.json`);

  fs.writeFileSync(tempPayloadPath, JSON.stringify(invoicePayload, null, 2), 'utf8');

  try {
    return await runPythonScript(helperPath, [tempPayloadPath]);
  } finally {
    fs.rmSync(tempPayloadPath, { force: true });
  }
}

async function saveInvoice(payload) {
  if (!Array.isArray(payload.products) || payload.products.length === 0) {
    throw new Error('Please select at least one product.');
  }

  const db = openDatabase();

  try {
    db.exec('BEGIN TRANSACTION');

    for (const item of payload.products) {
      const row = db.prepare('SELECT quantity FROM inventory_items WHERE id = ?').get(item.inventoryItemId);
      if (!row) {
        throw new Error('A selected product no longer exists in inventory.');
      }
      const available = Number(row.quantity || 0);
      const qty = Number(item.quantity || 0);
      if (qty <= 0) {
        throw new Error('Selected product quantity must be greater than zero.');
      }
      if (qty > available) {
        throw new Error(`Insufficient stock for product ID ${item.inventoryItemId}. Available: ${available.toFixed(2)}`);
      }
    }

      const createdAt = new Date().toISOString();
      const invoiceDate = payload.invoiceDate || createdAt.slice(0, 10);
      const toText = (payload.toText || '').trim();
    const totalQty = payload.products.reduce((sum, item) => sum + Number(item.quantity || 0), 0);
    const customerName = toText ? toText.split(/\r?\n/)[0] : '';
    const serviceType = payload.products.map((item) => item.productDescription || '').join(', ');

    const result = db.prepare(`
      INSERT INTO invoices (
        invoice_no, customer_name, total, created_at, service_type, phone, paid_amount,
        payment_mode, str_no, ntn_no, bill_no, delivery_challan_no, order_contract_no,
        order_date, inspection_note_no, invoice_date, to_text
      )
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `).run(
        payload.fileNo,
        customerName,
        totalQty,
      createdAt,
      serviceType,
      '',
      0,
      '',
        '',
        '',
        payload.billNo,
        payload.deliveryChallanNo,
        payload.orderContractNo,
        payload.orderDate,
        payload.inspectionNoteNo,
        invoiceDate,
        toText
      );

    for (const item of payload.products) {
      db.prepare(`
        INSERT INTO invoice_items (
          invoice_id, inventory_item_id, product_description, quantity, unit_price
        )
        VALUES (?, ?, ?, ?, ?)
      `).run(
        result.lastInsertRowid,
        item.inventoryItemId,
        item.productDescription,
        item.quantity,
        item.unitPrice
      );

      db.prepare('UPDATE inventory_items SET quantity = quantity - ? WHERE id = ?').run(
        item.quantity,
        item.inventoryItemId
      );
    }

    db.prepare(`
      INSERT OR IGNORE INTO payments (
        invoice_id,
        bill_no,
        institution_name,
        invoice_date,
        status,
        created_at
      )
      VALUES (?, ?, ?, ?, ?, ?)
      `).run(
        result.lastInsertRowid,
        payload.billNo,
        customerName,
        invoiceDate,
        'pending',
        createdAt
      );

    db.exec('COMMIT');

    const inventorySnapshot = new Map(
      payload.products.map((item) => {
        const inventoryRow = db.prepare(`
          SELECT reg_no, batch_no, mfg_date, exp_date, product_description
          FROM inventory_items
          WHERE id = ?
        `).get(item.inventoryItemId);

        return [item.inventoryItemId, inventoryRow || {}];
      })
    );

      const pdfPayload = {
        fileNo: payload.fileNo || String(result.lastInsertRowid),
        billNo: payload.billNo,
        outputDir: getInvoicesDir(),
        deliveryChallanNo: payload.deliveryChallanNo,
        orderContractNo: payload.orderContractNo,
        orderDate: payload.orderDate,
        inspectionNoteNo: payload.inspectionNoteNo,
        invoiceDate,
        toText,
        products: payload.products.map((item) => {
        const inventoryItem = inventorySnapshot.get(item.inventoryItemId) || {};
        return {
          regNo: inventoryItem.reg_no || '',
          batchNo: inventoryItem.batch_no || '',
          mfgDate: inventoryItem.mfg_date || '',
          expDate: inventoryItem.exp_date || '',
          productDescription: inventoryItem.product_description || item.productDescription || '',
          quantity: item.quantity,
          unitPrice: item.unitPrice,
        };
      }),
    };

    try {
      const pdfResult = await generateInvoicePdf(pdfPayload);
      return {
        ok: true,
        invoiceId: Number(result.lastInsertRowid),
        pdfPath: pdfResult.path || '',
      };
    } catch (pdfError) {
      return {
        ok: true,
        invoiceId: Number(result.lastInsertRowid),
        pdfPath: '',
        pdfError: pdfError.message,
      };
    }
  } catch (error) {
    db.exec('ROLLBACK');
    throw error;
  } finally {
    db.close();
  }
}

async function generateInvoicePdfForInvoice(invoiceId) {
  const pdfPayload = getInvoicePdfPayload(invoiceId);
  const pdfResult = await generateInvoicePdf(pdfPayload);
  return {
    ok: true,
    pdfPath: pdfResult.path || '',
  };
}

function createWindow() {
  const window = new BrowserWindow({
    width: 1440,
    height: 920,
    minWidth: 1100,
    minHeight: 720,
    backgroundColor: '#f4f1ea',
    autoHideMenuBar: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  window.loadFile(path.join(__dirname, 'renderer', 'index.html'));
}

ipcMain.handle('app:bootstrap', async () => {
  return bootstrapDataLayer();
});

ipcMain.handle('auth:login', async (_event, credentials) => authenticate(credentials));
ipcMain.handle('invoices:list', async () => listInvoicesAny());
ipcMain.handle('orders:list', async () => listOrdersAny());
ipcMain.handle('payments:list', async () => listPaymentsAny());
ipcMain.handle('inventory:list', async () => listInventoryAny());
ipcMain.handle('inventory:save', async (_event, payload) => saveInventoryItemAny(payload));
ipcMain.handle('inventory:update', async (_event, payload) => updateInventoryItemAny(payload));
ipcMain.handle('invoices:save', async (_event, payload) => saveInvoiceAny(payload));
ipcMain.handle('invoices:generatePdf', async (_event, invoiceId) => generateInvoicePdfForInvoiceAny(invoiceId));
ipcMain.handle('orders:save', async (_event, payload) => saveOrderAny(payload));
ipcMain.handle('payments:updateStatus', async (_event, payload) => updatePaymentStatusAny(payload));
ipcMain.handle('shell:openPath', async (_event, targetPath) => shell.openPath(targetPath || ''));
ipcMain.handle('dialog:pickOrderFile', async () => {
  const result = await dialog.showOpenDialog({
    title: 'Select Order File',
    properties: ['openFile'],
    filters: [
      { name: 'PDF and Images', extensions: ['pdf', 'png', 'jpg', 'jpeg', 'webp', 'bmp'] },
      { name: 'PDF', extensions: ['pdf'] },
      { name: 'Images', extensions: ['png', 'jpg', 'jpeg', 'webp', 'bmp'] },
    ],
  });

  if (result.canceled || !result.filePaths?.length) {
    return { canceled: true, filePath: '', fileName: '' };
  }

  return {
    canceled: false,
    filePath: result.filePaths[0],
    fileName: path.basename(result.filePaths[0]),
  };
});

ipcMain.handle('dialog:error', async (_event, options) => {
  await dialog.showMessageBox({
    type: 'error',
    title: options.title || 'Error',
    message: options.message || 'Something went wrong.',
  });
});

ipcMain.handle('dialog:info', async (_event, options) => {
  await dialog.showMessageBox({
    type: 'info',
    title: options.title || 'Info',
    message: options.message || '',
  });
});

app.whenReady().then(() => {
  createWindow();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});
